## Advanced InSAR techniques

Persistent or Permanent Scatterer techniques are a relatively recent development from conventional InSAR, and rely on studying pixels which remain coherent over a sequence of interferograms. In 1999, researchers at Politecnico di Milano, Italy, developed a new multi-image approach in which one searches the stack of images for objects on the ground providing consistent and stable radar reflections back to the satellite. These objects could be the size of a pixel or, more commonly, sub-pixel sized, and are present in every image in the stack. 
Some research centres and other companies, like the Dutch TU Delft spin-off Hansje Brinker, were inspired to develop their own algorithms which would also overcome InSAR's limitations. In scientific literature, these techniques are collectively referred to as Persistent Scatterer Interferometry or PSI techniques. The term Persistent Scatterer Interferometry (PSI) was created by ESA to define the second generation of radar interferometry techniques.

Source: Wikipedia [Interferometric synthetic aperture radar](http://en.wikipedia.org/w/index.php?title=Interferometric_synthetic_aperture_radar&oldid=653765513 "this version")

#### Repositories
