## The Thematic Exploitation Platforms (TEPs) activity originated by ESA

The geohazards platform or GEP serves as a means to support the use of satellite EO for geohazards risk assessment. It is an evolution of ESA’s Supersites Exploitation Platform (SSEP) which is based on the ESA Grid Processing on Demand (G-POD) processing environment and was developed for specialized exploitation of EO data resources in the context of the Geohazard Supersites & Natural Laboratories and since then has been expanded to address objectives of the broader geohazards community. In parallel to geohazards ESA is preparing other satellite EO based Thematic Exploitation Platforms (TEPs) top address other themes i.e. hydrology, polar, costal, forestry and urban. These TEPs serve a unique role in that they both facilitate access and processing of large datasets and federate communities of users around common goals, promoting shared science objectives and better use of satellite EO.

The platform is meant to allow users to easily exploit EO data resources by combining fast data access, processing facilities and flexibility for the user own data analysis. The platform provides Data Access, Data Processing Services and PaaS (Platform as a Service). Data Access includes the possibility to perform catalogue queries. Data Processing Services enable users to invoke processing of data available in the repository using a number of well know tools and exploit the results. PaaS enables users to perform their data exploitation activities with large flexibility and autonomy by using one or several virtual hosts directly provisioned on the Cloud platform where the data sits. Users can, therefore, use PaaS to efficiently access data and processing services and immediately elaborate the results using analysis and visualization tools available in PaaS or directly installed in the PaaS by the user. In addition users can also open their own accounts on the Cloud and directly provision their IaaS independently the Geohazards Platform Services.
